server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # React routing
    location / {
        try_files $uri /index.html;
    }

    # API Gateway proxy
    location /api/auth/ {
        proxy_pass http://auth-service.auth-service.svc.cluster.local:8000/;
    }

    location /api/room/ {
        proxy_pass http://room-service.room-service.svc.cluster.local:8000/;
    }

    location /api/booking/ {
        proxy_pass http://booking-service.booking-service.svc.cluster.local:8000/;
    }

    location /api/post/ {
        proxy_pass http://posts-service.posts-service.svc.cluster.local:8000/;
    }

    location /api/wallet/ {
        proxy_pass http://wallet-service.wallet-service.svc.cluster.local:8000/;
    }

    # Headers (important for Django + cookies)
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}