apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.appname" (dict "ctx" $ "svc" "frontend") }}
  labels:
    app: {{ include "helm.appname" (dict "ctx" $ "svc" "frontend") }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    app: {{ include "helm.appname" (dict "ctx" $ "svc" "frontend") }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
  type: {{ .Values.service.type }}